### ISSUE TITLE
Traverse over active file instead of picking one from the extension panel

### ISSUE THREAD

**Issue by adielhercules** [oslabs-beta/sapling#87]
When traversing a file that is not the top component in the hierarchy I have to pick a new one in order to inspect it.

So, I would suggest to rather automatically traverse the file I have in open in the active editor.

As an alternative it could be that it can let you pick a file in the current project with a dialog similar to the file switcher dialog of the VSCode editor, that could also be handy.

**Comment by hienqn** [comment]
Good idea! I pulled in the change by @tdranv and it's working.

**Comment by charlesgutwirth** [comment]
@adielhercules Thank you for the issue post! We took a look at @tdranv's pull request, but we believe it would be too intrusive to the user experience if the tree rebuilds each time the user opens a file. It would automatically collapse the tree each time the active file changes, inherently forcing the user to reopen the tree nodes in order to view the component hierarchy. Thank you again for the issue, and we look forward to hearing more feature suggestions in the future!
